name: Build & Deploy

on:
  repository_dispatch:
    types: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@master
      -
        name: build
        run: |
          make build
      -  
        name: test
        run: |
          make test
      - 
        name: release
        run: |
          make release
